version: '3.8'

volumes:
  mysql_data:

x-common-variables:
  &common-api-variables
  PYTHONDONTWRITEBYTECODE: 1
  DB_HOST: "${DB_HOST?}"
  DB_SCHEMA: "${DB_SCHEMA?}"
  DB_USERNAME: "${DB_USERNAME?}"
  DB_PASSWORD: "${DB_PASSWORD?}"
  NETWORK_NAME: "${NETWORK_NAME?}"
  DADO_SENSIVEL: "${DADO_SENSIVEL?}"


services:
  project:
    build:
      context: .
    command: python3 app/main.py
    restart: always
    environment:
      <<: *common-api-variables
      LOG_LEVEL: "debug"
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line and delete the one above
    #image: mysql:8
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--general-log=1',
      '--general-log-file=/var/lib/mysql/my-general.log',
      '--slow-query-log=1',
      '--slow-query-log-file=/var/lib/mysql/my-slow-query.log',
      '--log_error=/var/lib/mysql/my-error.log',
      '--sql-mode=NO_ENGINE_SUBSTITUTION',
      '--ngram_token_size=1',
    ]
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_SCHEMA}"
      MYSQL_USER: "${DB_USERNAME?}"
      MYSQL_PASSWORD: "${DB_PASSWORD?}"
    logging:
      options:
        max-size: "5m"
    ports:
      - 33060:3306

networks:
  default:
    name: "${NETWORK_NAME}"